//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlexInfoModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class ARTIKLAR
    {
        public string ARTNR { get; set; }
        public string TEXT { get; set; }
        public string SOKTEXT2 { get; set; }
        public string unTextGroup { get; set; }
        public string KLASS { get; set; }
    }
}
