//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlexInfoModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class KUNDER
    {
        public string KUNDNR { get; set; }
        public string NAMN { get; set; }
        public string ORGNR { get; set; }
        public string TEL { get; set; }
        public string LevNamn { get; set; }
        public string LevADR { get; set; }
        public string LevPOSTADR { get; set; }
    }
}
